infrastructure/mgmt.tfvars
scripts/action-infra-stack.sh
scripts/bootstrapper.sh
scripts/project-common.sh

Bootstrapper script changed to accept mgmt as an account type and tf vars to recognise new repo
---

Tweak bootstrapper for mgmt style account

---

.github/actions/cloc/action.yaml
.github/actions/code-line-count/action.yaml
.github/actions/derive-tf-version/action.yaml
.github/actions/metadata/action.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-app-develop.yaml

DR-596 Add Metadata reusable and supporting actions

---

scripts/config/.gitleaks.toml

DR-596 Update toml to handle docs

---

.github/actions/checkout-repository/action.yaml
.github/workflows/metadata.yaml

The purpose here is to provide an option of checking out from a different code repository and a given tag from the code repositories history
---

DR-596 Checkout action wrapper

---

.github/actions/check-eslint/action.yaml
.github/actions/check-format-general/action.yaml
.github/actions/check-format-markdown/action.yaml
.github/actions/check-format-python/action.yaml
.github/actions/check-format-terraform/action.yaml
.github/actions/check-syntax-python/action.yaml
.github/actions/derive-tf-version/action.yaml
.github/actions/scan-secrets/action.yaml
.github/actions/validate-terraform/action.yaml
.github/workflows/quality_checks.yaml

DR-596 Switch quality check flow to main

---

.github/actions/install-python/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/unit_test.yaml
application-utils/common/utilities.py
application/hello-world/greeting.py
application/hello-world/test/requirements.txt
application/hello-world/test/test_greeting.py
scripts/run-test-coverage.sh

Add reusable unit test workflow and python unit test action
---

DR-596 Add unit test workflow

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/metadata.yaml
.github/workflows/quality_checks.yaml
.github/workflows/unit_test.yaml
scripts/v2/derive-workspace.sh

DR-596 Refactor derive workspace script

---

scripts/workflow/action-infra-stack.sh

DR-596 Patch worflow version 0.3

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/metadata.yaml
.github/workflows/quality_checks.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/unit_test.yaml
application-utils/common/test/requirements.txt
application-utils/common/test/test_utilities.py
scripts/workflow/run-test-coverage.sh

DR-452 Enable targeted unit test runs

---

infrastructure/stacks/test-stack-1/s3.tf
infrastructure/stacks/test-stack-2/s3.tf

DR-5961 Updated name of test buckets

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/build-and-deploy-application.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality_checks.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/unit_test.yaml
scripts/workflow/README.md
scripts/workflow/action-infra-stack.sh
scripts/workflow/bootstrapper.sh

DR-596 Refactor bootstrapper script and add new workflow

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/derive-workspace/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/build-and-deploy-application.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration_test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality_checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/unit_test.yaml
scripts/workflow/derive-workspace.sh

DR-798 Add github event ref to drive workspace logic

---

.github/workflows/test-cleardown.yaml

DR-798 Move version to activate cleardown

---

.github/workflows/infrastructure-cleardown.yaml

Quality run check. For consistency changed input for stacks from array --> json to json --> array. 
https://nhsd-jira.digital.nhs.uk/browse/DR-798
To 
---

DR-7983 Input stacks from json

---

.github/workflows/infrastructure-cleardown.yaml

Revert stacks input array back to orginal.
---

DR-7983 Revert input stack json

---

.github/workflows/infrastructure-cleardown.yaml
scripts/workflow/cleardown-terraform-state.sh

Fix "not a valid identifier" for delete terraform state file.
https://nhsd-jira.digital.nhs.uk/browse/DR-798
---

DR-7984 pipeline infra cleardown

---

.github/actions/cleardown-tf-state/action.yaml

Modify cleardown-tf-state/action.yaml stacks to stack
https://nhsd-jira.digital.nhs.uk/browse/DR-798
---

DR-7984 Pipeline cleardown dev

---

.github/workflows/infrastructure-cleardown.yaml
scripts/workflow/cleardown-terraform-state.sh

Change destroy-application-infrastructure uses path.
https://nhsd-jira.digital.nhs.uk/browse/DR-798
---

DR-7985 pipeline infra cleardown

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/build-and-deploy-application.yaml
.github/workflows/build-and-deploy-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
infrastructure/local/versions.tf
infrastructure/modules/lambda/variables.tf
infrastructure/remote/versions.tf
scripts/config/sonar-scanner.properties

DR-630 Uplift python version

---

infrastructure/stacks/github-runner/role.tf

DR-630 Handle indented policy

---

scripts/workflow/run-test-coverage.sh

Modify test coverage script to support data-migration in uec-dos-service-management
---

DR-824 Modify test coverage script

---

scripts/workflow/bootstrapper.sh

DR-871 Temp apply in bootstrapper

---

.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-react-app-develop.yaml

Extend timeout for two jobs that can come close to and occasionally exceed the default
---

DR-913 Extend timeout where needed

---

infrastructure/stacks/dos-artefacts/s3.tf
infrastructure/stacks/dos-artefacts/variables.tf

DR-915 Align artefact repositories with domain repo name

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/artefact-cleardown/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/build-application.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-build-and-deploy.yaml
.github/workflows/test-cleardown.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
scripts/workflow/cleardown-artefacts.sh

DR-919 Cleardown old artefacts

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/artefact-cleardown/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-cleardown.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml

PR to restrict artefacts clear down and have a dedicated workflow
---

DR-960 Restrict artefacts cleardown

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-cleardown.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf
infrastructure/stacks/dos-artefacts/bucket-policies-sm.tf
infrastructure/stacks/dos-artefacts/bucket-policies-ss.tf
infrastructure/stacks/dos-artefacts/bucket-policies-ui.tf
infrastructure/stacks/dos-artefacts/bucket-policies-um.tf
infrastructure/stacks/dos-artefacts/data.tf
infrastructure/stacks/dos-artefacts/variables.tf
scripts/workflow/action-infra-stack.sh
scripts/workflow/bootstrapper.sh

DR-971 Replace variables with data lookup

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml

DR-904 Revert latest tag

---

.github/workflows/test-build-and-deploy.yaml
.github/workflows/test-build-full-app-int.yaml

DR-930 Domain bug fix

---

infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf
infrastructure/stacks/dos-artefacts/bucket-policies-sm.tf
infrastructure/stacks/dos-artefacts/bucket-policies-ss.tf
infrastructure/stacks/dos-artefacts/bucket-policies-ui.tf
infrastructure/stacks/dos-artefacts/bucket-policies-um.tf

DR-930 Add tagging permission to bucket pol

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
scripts/workflow/run-test-coverage.sh

DR-795 Handle python config files

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf

DR-795 Support bootstrap of preprod

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-full-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml

DR-929 Matrix domain fail fast false

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml

DR-1000 Change tag to latest

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml
infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf
infrastructure/stacks/dos-artefacts/data.tf
scripts/workflow/action-infra-stack.sh
scripts/workflow/bootstrapper.sh

DR-1048 Add prototype and move to v36

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
infrastructure/stacks/parameter_store/ssm-parameters.tf

DR-985 Add parameter store stack

---

.github/workflows/artefacts-cleardown.yaml
.github/workflows/infrastructure-cleardown.yaml

DR-1065 Bump teardown timeout

---

.github/actions/action-infrastructure-stack/action.yaml
.github/actions/checkout-repository/action.yaml
.github/actions/unit-test-python/action.yaml
.github/workflows/artefacts-cleardown.yaml
.github/workflows/build-application.yaml
.github/workflows/build-react-app.yaml
.github/workflows/deploy-infrastructure.yaml
.github/workflows/deploy-lambda-code.yaml
.github/workflows/deploy-react-app.yaml
.github/workflows/generate-tag-name.yaml
.github/workflows/infrastructure-cleardown.yaml
.github/workflows/integration-test.yaml
.github/workflows/metadata.yaml
.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/quality-checks.yaml
.github/workflows/tag-repository.yaml
.github/workflows/test-sparse-checkout-flow.yaml
.github/workflows/ui-test.yaml
.github/workflows/unit-test.yaml

DR-1065 Move latest tag

---

infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf
infrastructure/stacks/dos-artefacts/bucket-policies-sm.tf

DR-1065 Prod cm github runner access

---

.github/actions/derive-artefact-address/action.yaml
.github/workflows/derive-artefact-address.yaml

Re-usuable workflow to derive artefact address
---

DR-1013 Implement preprod worflow

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml

DR-1079 Update deploy acc infra pipeline

---

.github/CODEOWNERS

DR-999 Add codeowners file

---

.github/actions/derive-workspace/action.yaml
scripts/workflow/derive-workspace.sh

DR-800 Remove branch name export

---

infrastructure/stacks/dos-artefacts/bucket-policies-cm.tf
infrastructure/stacks/dos-artefacts/s3.tf
infrastructure/stacks/dos-artefacts/variables.tf

…he prototype
Added artefact bucket & policy for prototype to accommodate the CM prototype being moved to its own [repo](https://github.com/NHSDigital/uec-cm-prototype).

DR-1130 Add artefact bucket & policy for prototype

---

.github/actions/check-tf-state/action.yaml
.github/workflows/infrastructure-cleardown.yaml
scripts/workflow/check-terraform-state.sh

Add safeguard against incomplete cleardown of non default terraform state

DR-1180 Add tf cleardown check

---

.github/workflows/test-cleardown.yaml

Having re-tested the unhappy path ...

DR-1180 Add missing stacks

---

scripts/workflow/check-terraform-state.sh

DR-1182 Refine file check

---

.github/actions/install-python/action.yaml
.github/workflows/slack-notifications.yaml

Upgrade the following packages to versions compatible with Node.js 20:
- actions/setup-python
- technote-space/workflow-conclusion-action (Note: workflow-conclusion-action is no longer supported and can only be upgraded to a maximum of Node.js 17.)

DR-1008 Upgrade packages that use nodejs 20

---

.github/workflows/slack-notifications.yaml

Replace technote space workflow conclusion GitHub action

DR-1888 Replace technote space workflow conclusion GitHub action

---

scripts/workflow/derive-workspace.sh

FDOS-46 Set develop branch workspace
